server:
  port: 8080

spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://localhost:5433/pdp
    password: 123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true