spring:
  application:
    name: config-server
server:
  port: 8082
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#spring:
#  application:
#    name: UserService
#eureka:
#  instance:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka